initiative_reporting_authorization_header   = "AQICAHj/dDoeiJpNXN0B6L0zLKcVv4Jvrx7fUvDJb56PSn8rQQFZCnega+wNhvu/6sAdxHQ+AAAAgDB+BgkqhkiG9w0BBwagcTBvAgEAMGoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQM/abpOqMiIjqKQ+a9AgEQgD0FgRZCZADCYfwqR9Mbo6uBWQyygJsxud5nK6zYA+XuDeJ5KOLS0OjF1rsBNoOK9c1Shl83hHhq5qsmgV2J"
architecture_reporting_authorization_header = "AQICAHj/dDoeiJpNXN0B6L0zLKcVv4Jvrx7fUvDJb56PSn8rQQEAqfbewljF4/8e1Fi4CyZJAAAAgDB+BgkqhkiG9w0BBwagcTBvAgEAMGoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMlYMTNBOhF/t7tR8NAgEQgD2oYes2lig4L/MMwe2oOJS4MSTxdnxSevWrTio4oPrtC52luoSv4pnVaFnQRq5G7LftVHqkApUMOl93DeXC"
confluence_url                              = "https://humm-group.atlassian.net"
confluence_email                            = "ryan.bartsch@humm-group.com"
initiative_reporting_confluence_token       = "AQICAHj/dDoeiJpNXN0B6L0zLKcVv4Jvrx7fUvDJb56PSn8rQQF1qZmhaC0Tivd7x3y40W9oAAABJzCCASMGCSqGSIb3DQEHBqCCARQwggEQAgEAMIIBCQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAzoXVQ8ICfzThxHI0kCARCAgdvVVPN1insf4UGsebB1nSZkN7Y8ga7fzYbz/4G60v2zYwa/IlSyeQiTA5HymtBWfwCdWza0Q9vAR0MT71Z7q+vYi2tz7l24yBv38MP65zbo6SpwS7TmbGiohcEY4m49D8d5FlDqepc1/E2qKJU9Qb6IuqeNN9iH5Q3G9KBwv0QGOZ3LgV/I2fHVQxemDLTAwrYjgIKL4GEfrlBxLQXUImopGd+lbWY0M6g+WIyBg7NWkHd6TwUTTRxgGRholSpsasEgyu+1wZzAw7ICe4IOAtmhO4wdsJABxxeiCdg="
architecture_reporting_confluence_token     = "AQICAHj/dDoeiJpNXN0B6L0zLKcVv4Jvrx7fUvDJb56PSn8rQQETGdFjcfcnxVv6CNWnz/T8AAABJzCCASMGCSqGSIb3DQEHBqCCARQwggEQAgEAMIIBCQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAy6a4/XUjWuE1lE3+UCARCAgdtQBqTdOIo6u3HTNTvE5lyHHqn+DtKnOCoSfiTEJCwI2GCvA/xwNsRH3fiLRObq4wUNWlTrnT3ip7ri0Nl1aDix41LGpP8kCDIu8b6tgy7oKNEcoOsCL7O8PCDaLbQeJnSyojN5ojsUIfac7Yu3dcLKXMgQ7PvT1x9025lJscWdZzqoDm77RwQZaBM2nwJatbybni5gO0zqRj/CrcfigqUIrA3D3smY8/JIbHlBToDxQz6temHvef6ylPKK6tSmilS/szsTbWHqxS0zFJAqZv8h7AtJQp2KFyKZ1Q4="
confluence_space_id                         = "ADVE"
elastic_url                                 = "https://sandbox.es.ap-southeast-2.aws.found.io"
initiative_report_elastic_datastream        = "docs-initiatives.reporting-prod"
architecture_report_elastic_datastream      = "docs-architecture.reporting-prod"
initiative_reporting_elastic_api_key        = "AQICAHj/dDoeiJpNXN0B6L0zLKcVv4Jvrx7fUvDJb56PSn8rQQFtuKhhV3M+Zk6oaFhaZdPFAAAAnjCBmwYJKoZIhvcNAQcGoIGNMIGKAgEAMIGEBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDIv1hgZshN56GGnQaAIBEIBXQSdiXHDgPs1sVfGxYxYktrt4v8T8gyh/fLBYOXhLpeewJ7CUP3cIcDcWC2MG3q/GGiAdkKDZMHEV6/+JG1wT5G/oWVfUtupo4bRCfgwZ+kSkNU2tXsS7"
architecture_reporting_elastic_api_key      = "AQICAHj/dDoeiJpNXN0B6L0zLKcVv4Jvrx7fUvDJb56PSn8rQQGqAGHj3aj4hSBGmFpKViubAAAAnjCBmwYJKoZIhvcNAQcGoIGNMIGKAgEAMIGEBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDNPOnd2fOnjHJVz4HwIBEIBXQw1TRSd/th9aq26IMS6A5tapONUb0EWEQWvMT09KjGzvEaTO4kOfGfOcM94pNJx2JjIYjUAcrumMjdOqWEgTXC3iol91KJY3g8QBXIAkTK94RngU1dN9"
initiative_report_elastic_watcher_id        = "74bddc42-20e7-48cc-be6a-64bda99aa0be"
architecture_report_elastic_watcher_id      = "13360196-6796-4287-9fee-e713c887339e"
initiative_report_schedule_expression       = "cron(0 12 ? * 5 *)"
architecture_report_schedule_expression     = "cron(0 11 ? * 5 *)"
