lambda_authorization_header             = "AQICAHgHcOIBQwvf1sWEeOKBRfSGuOr65EI9OafsAZRPbokJ/QHUEuHPsyv2uyNGcNIJ6b9bAAAAgDB+BgkqhkiG9w0BBwagcTBvAgEAMGoGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMg9SpeHlRjBbGkrULAgEQgD1rGI8+v2pipnDJgYeMx4mZhCxsUiOzXWNYOOjiKsilenclb2AFqOkbUc65fCbiNQb4wyJT98NqUF/h+OG+"
confluence_url                          = "https://humm-group.atlassian.net"
confluence_email                        = "ryan.bartsch@humm-group.com"
confluence_token                        = "AQICAHgHcOIBQwvf1sWEeOKBRfSGuOr65EI9OafsAZRPbokJ/QGaU6xqr5+n/p953HXi176IAAABJzCCASMGCSqGSIb3DQEHBqCCARQwggEQAgEAMIIBCQYJKoZIhvcNAQcBMB4GCWCGSAFlAwQBLjARBAwO6Y2LOgasX534k2ACARCAgdupSxr9JmG9eZjSGVmlImm6jrB7QW7q/IrZbf4zwwiTF+LsgvV8WsZ8BY6+iqeMtr5RiiJbSzX6Fo9/xzk+h/L99kUUB0Izi4dOFHWdfxfohWsmOCgYltgrVOgvEJv1AHC9dbzAA+FUxyG2Pgt73qV/MQncdG+Xfyokf8ce1bjnnxl7se498VcF8yaQZayPdCRMb5WyrcgSWsanbLVNLHK41D08avRu1WxhhuVUz+jMczn+v8ah5wQv2tOv7ltF2Cq6d8UZimTyLLoFqx7Q0r/Jb6JmSuoL/5qq9gw="
confluence_space_id                     = "ADVE"
elastic_url                             = "https://sandbox.es.ap-southeast-2.aws.found.io"
initiative_report_elastic_datastream    = "docs-initiatives.reporting-prod"
architecture_report_elastic_datastream  = "docs-architecture.reporting-prod"
elastic_api_key                         = "AQICAHgHcOIBQwvf1sWEeOKBRfSGuOr65EI9OafsAZRPbokJ/QFfYbNB3V5gb/xD4joaNWIPAAAAnjCBmwYJKoZIhvcNAQcGoIGNMIGKAgEAMIGEBgkqhkiG9w0BBwEwHgYJYIZIAWUDBAEuMBEEDG9keyazitVS2CtOEgIBEIBXZtJjL2rjvpT+78oMti9qIvK1btlLxth659voMs54lszt5YYpoUNg76pYqeVe311G1QiehFMYtXdXjgwj3fYSNd9p8AREr9ffDtahdul2C8jIWJLYedbj"
initiative_report_elastic_watcher_id    = "74bddc42-20e7-48cc-be6a-64bda99aa0be"
architecture_report_elastic_watcher_id  = "13360196-6796-4287-9fee-e713c887339e"
initiative_report_schedule_expression   = "cron(0 12 ? * 5 *)"
architecture_report_schedule_expression = "cron(0 11 ? * 5 *)"
